FROM node:16

ENV CI=true

WORKDIR /app

COPY package.json ./

RUN npm install

COPY ./ ./

#install R and packages
#RUN add-apt-repository universe multiverse
RUN apt update

RUN apt-get install -y r-base
RUN apt-get install -y -qq r-cran-teachingdemos
RUN apt-get install -y -qq r-cran-qqman

#RUN R -e "install.packages(c('TeachingDemos'),dependencies=TRUE,repos='http://cran.rstudio.com/')"

#remove windows line endings
RUN apt-get install dos2unix
RUN dos2unix pipeline_scripts/smr.sh
RUN chmod 775 pipeline_scripts/smr.sh

RUN dos2unix pipeline_scripts/smr_plot.sh
RUN chmod 775 pipeline_scripts/smr_plot.sh

#RUN yarn run build
CMD [ "npm", "run", "start:dev" ]
